language: csharp

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      dotnet: 3.0
    - os: osx
      osx_image: xcode8.3
      dotnet: 3.0

branches:
  only:
    - "master"

before_script:
  - if test "$TRAVIS_OS_NAME" == "osx"; then export FrameworkPathOverride=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/4.5/; else export FrameworkPathOverride=/usr/lib/mono/4.5/; fi

script:
  - git fetch --unshallow --tags
  # disengage core only switch because mono ships .NETFramework targets
  - ./build.sh --coreonly=false --linksources=true --verbosity=verbose
